RegisterViewModelBase.h: add <memory> for unique_ptr
Without the change gcc-12 fails to build edb-debugger as:

    [ 20%] Building CXX object src/CMakeFiles/edb.dir/RegisterViewModelBase.cpp.o
    In file included from edb-debugger/src/RegisterViewModelBase.cpp:18:
    edb-debugger/include/RegisterViewModelBase.h:162:14: error:
      'unique_ptr' in namespace 'std' does not name a template type
      162 |         std::unique_ptr<CategoriesHolder> rootItem;
          |              ^~~~~~~~~~
    edb-debugger/include/RegisterViewModelBase.h:9:1: note:
      'std::unique_ptr' is defined in header '<memory>';
        did you forget to '#include <memory>'?
        8 | #include <deque>
      +++ |+#include <memory>